spring.application.name=rating-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/cakedelight_rating
spring.datasource.username=root
spring.datasource.password=Najim@4633
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true