services:
  mysql-db:
    image: mysql:8.0
    container_name: cakedelight-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cakedelight-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cakedelight-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cakedelight-network

  catalog-service:
    build:
      context: ../catalog-service
    container_name: cakedelight-catalog
    ports:
      - "8081:8081"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - cakedelight-network

  order-service:
    build:
      context: ../order-service
    container_name: cakedelight-order
    ports:
      - "8082:8082"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mysql-db
      - rabbitmq
    networks:
      - cakedelight-network

  rating-service:
    build:
      context: ../rating-service
    container_name: cakedelight-rating
    ports:
      - "8083:8083"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - cakedelight-network

  notification-service:
    build:
      context: ../notification-service
    container_name: cakedelight-notification
    ports:
      - "8084:8084"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mysql-db
      - rabbitmq
    networks:
      - cakedelight-network

  api-gateway:
    build:
      context: ../api-gateway
    container_name: cakedelight-gateway
    ports:
      - "8090:8080"
    depends_on:
      - catalog-service
      - order-service
      - rating-service
      - notification-service
    networks:
      - cakedelight-network

  frontend:
    build:
      context: ../frontend
    container_name: cakedelight-frontend
    ports:
      - "8085:3000"
    depends_on:
      - api-gateway
    networks:
      - cakedelight-network

volumes:
  mysql-data:

networks:
  cakedelight-network:
    driver: bridge
