apiVersion: v1
kind: Secret
metadata:
  name: cakedelight-secrets
type: Opaque
data:
  # MySQL Credentials
  mysql-user: cm9vdA== # "root"
  mysql-password: cm9vdDEyMw== # "root123"
  mysql-root-password: cm9vdDEyMw== # "root123"

  # RabbitMQ Credentials (Kubernetes will use this to set up the container)
  rabbitmq-user: Z3Vlc3Q= # "guest"
  rabbitmq-password: Z3Vlc3Q= # "guest"
